# Generated by Django 5.2.3 on 2025-08-16 15:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imprest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imprest_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('name_of_holder', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('amount_generated', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_generated', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=10)),
                ('date_confirmed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
