# Generated by Django 5.2.3 on 2025-11-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningguide',
            options={},
        ),
        migrations.RemoveField(
            model_name='learningguide',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='learningguide',
            name='document',
        ),
        migrations.RemoveField(
            model_name='learningguide',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='learningguide',
            name='html_content',
        ),
        migrations.RemoveField(
            model_name='learningguide',
            name='level',
        ),
        migrations.RemoveField(
            model_name='learningguide',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='learningguide',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='learningguide',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='learningguide',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='learningguide',
            name='date_preparation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningguide',
            name='date_revision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningguide',
            name='institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='learningguide',
            name='sessions_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningguide',
            name='term',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='learningguide',
            name='total_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningguide',
            name='trainees',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='learningguide',
            name='trainer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='learningguide',
            name='unit_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='learningguide',
            name='unit_competence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
