# Generated by Django 5.2.3 on 2025-11-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_alter_learningguide_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningguide',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
