# Generated by Django 5.2.3 on 2025-11-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_learningguide_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningguide',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningguide',
            name='sessions_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
