# Generated by Django 5.2.3 on 2025-11-23 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_learningguide_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSessionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_title', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('presenter_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('bridge_in', models.CharField(blank=True, max_length=50)),
                ('pre_assessment', models.CharField(blank=True, max_length=50)),
                ('post_assessment', models.CharField(blank=True, max_length=50)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('expectation', models.TextField(blank=True)),
                ('trainer_activities', models.TextField(blank=True)),
                ('trainee_activities', models.TextField(blank=True)),
                ('resources', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.learningguide')),
            ],
        ),
    ]
