# Generated by Django 5.2.3 on 2025-11-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_savedsessionplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsessionplan',
            name='bridge_in',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='savedsessionplan',
            name='post_assessment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='savedsessionplan',
            name='pre_assessment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='savedsessionplan',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
