# Generated by Django 5.2.3 on 2025-11-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_alter_savedsessionplan_bridge_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsessionplan',
            name='bridge_in',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='savedsessionplan',
            name='post_assessment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='savedsessionplan',
            name='pre_assessment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='savedsessionplan',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
