# Generated by Django 5.2.3 on 2025-11-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0007_alter_savedsessionplan_bridge_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsessionplan',
            name='time',
            field=models.TextField(blank=True),
        ),
    ]
