# Generated by Django 5.2.3 on 2025-11-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflection',
            name='assessment_type',
            field=models.CharField(choices=[('cat', 'CAT'), ('exam', 'Final Exam'), ('assignment', 'Assignment'), ('project', 'Project'), ('practical', 'Practical'), ('general', 'General Learning')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='reflection',
            name='term',
            field=models.CharField(blank=True, choices=[('term1', 'Term 1'), ('term2', 'Term 2'), ('term3', 'Term 3'), ('semester1', 'Semester 1'), ('semester2', 'Semester 2')], max_length=20),
        ),
        migrations.AddField(
            model_name='reflection',
            name='unit_code',
            field=models.CharField(blank=True, help_text='Unit/Course code', max_length=50),
        ),
        migrations.AddField(
            model_name='reflection',
            name='unit_name',
            field=models.CharField(blank=True, help_text='Unit/Course name', max_length=200),
        ),
    ]
