# Generated by Django 5.2.3 on 2025-11-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_reflection_assessment_type_reflection_term_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerdata',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='trainerdata',
            name='county',
        ),
        migrations.RemoveField(
            model_name='trainerdata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trainerdata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='trainerdata',
            name='highest_education',
        ),
        migrations.RemoveField(
            model_name='trainerdata',
            name='sub_county',
        ),
        migrations.RemoveField(
            model_name='trainerdata',
            name='town',
        ),
        migrations.AddField(
            model_name='trainerdata',
            name='current_appointment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerdata',
            name='current_jg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainerdata',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerdata',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerdata',
            name='employer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainerdata',
            name='first_appointment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainerdata',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainerdata',
            name='kin_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trainerdata',
            name='kin_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='trainerdata',
            name='kin_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trainerdata',
            name='kin_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trainerdata',
            name='special_responsibilities',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trainerdata',
            name='staff_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='trainerdata',
            name='courses',
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trainerdata',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainerdata',
            name='courses',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
