# Generated by Django 5.2.3 on 2025-11-10 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_trainerdata_certificates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerdata',
            name='o_level_certificate',
            field=models.FileField(blank=True, null=True, upload_to='trainer_docs/'),
        ),
        migrations.AddField(
            model_name='trainerdata',
            name='secondary_certificate',
            field=models.FileField(blank=True, null=True, upload_to='trainer_docs/'),
        ),
        migrations.AddField(
            model_name='trainerdata',
            name='tertiary_certificate',
            field=models.FileField(blank=True, null=True, upload_to='trainer_docs/'),
        ),
        migrations.CreateModel(
            name='TrainerOtherDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='trainer_others/')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_docs', to='home.trainerdata')),
            ],
        ),
    ]
